### ISSUE TITLE
environment ？ 

### ISSUE THREAD

**Issue by defineconst** [mvanmoer/eclipsegrdecl2vtk#1]
D:\ProgramData\Anaconda3\envs\pyGRDECL\python.exe "D:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 10179 --file E:/3000_3D_2020/eclipsegrdecl2vtk-master/eclipse2vtk.py
pydev debugger: process 54416 is connecting

Connected to pydev debugger (build 162.1967.10)
else section:  NOECHO

else section:  NOECHO

Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pydev\pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pydev\pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/3000_3D_2020/eclipsegrdecl2vtk-master/eclipse2vtk.py", line 218, in <module>
    ugrid = ConvertGrid(testfile)
  File "E:/3000_3D_2020/eclipsegrdecl2vtk-master/eclipse2vtk.py", line 64, in ConvertGrid
    xcoords = coords[0::3]
TypeError: 'map' object is not subscriptable

Process finished with exit code 1

**Comment by mvanmoer** [comment]
@defineconst This was developed against vtkpython when VTK still required Python 2. Please try Python 2.

**Comment by mvanmoer** [comment]
@defineconst I have made two small changes to support Python 3. Verifed against VTK 8.2.0 and Python 3.5.2.  See commit: 910e904
